name: Build and Release OnePlus 11 EmberHeart Kernel and Kernel Modules

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Select type of Github release?'
        required: true
        type: choice
        options:
          - none
          - Pre-release
          - Release
        default: none
      ksun_branch:
        description: 'Enter KernelSU Next Branch or commit hash (blank for stable tag)'
        required: true
        type: string
        default: next
      optimize_level:
        description: "Compiler optimization level"
        required: true
        type: choice
        options: [O2, O3]
        default: O2
      kernel_uname:
        description: 'Kernel uname'
        type: string
        default: 'EmberHeart'
      android13-5_15_susfs_branch_or_commit:
        description: 'Enter SusFS Branch or commit hash for android13-5.15'
        type: string
        default: ''

jobs:
  build-kernel:
    name: Build Kernel
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP11
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_11_v.xml
            android_version: android13
            kernel_version: '5.15'          
    runs-on: ubuntu-latest
    steps:
      - name: Resolve SUSFS branch from inputs
        id: susfs
        shell: bash
        run: |
          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
          SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
      
          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Kernel
        uses: ./.github/actions
        with:
          model: ${{ matrix.model }}
          soc: ${{ matrix.soc }}
          branch: ${{ matrix.branch }}
          manifest: ${{ matrix.manifest }}
          ksun_branch: ${{ inputs.ksun_branch }}
          susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
          optimize_level: ${{ inputs.optimize_level }}
          kernel_uname: ${{ inputs.kernel_uname }}
          
  build-kernel-modules:
    name: Build Kernel Modules
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP11
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_11_v.xml
            android_version: android13
            kernel_version: '5.15'
            
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Kernel Modules
        uses: ./.github/kernel_modules
        with:
          model: ${{ matrix.model }}
          soc: ${{ matrix.soc }}
          branch: ${{ matrix.branch }}
          manifest: ${{ matrix.manifest }}

  trigger-release:
    needs:
      - build-kernel
      - build-kernel-modules
    runs-on: ubuntu-latest
    if: ${{ inputs.release_type != 'none' }}
    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: 'OnePlus 11 EmberHeart Kernel With KernelSU Next, Nethunter & SUSFS v1.5.12'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download Wirless Firmware Module for Nethunter 
        id: download_external
        env:
          SOURCE_REPO: 0x-br0k3n/Nethunter-Wireless-Firmware 
        run: |
          echo "--- Downloading Latest Release Asset from $SOURCE_REPO ---"
          
          DOWNLOAD_DIR="./downloaded-artifacts/wireless-firmware"
          mkdir -p "$DOWNLOAD_DIR"
          
          LATEST_RELEASE_TAG=$(gh api \
            repos/$SOURCE_REPO/releases/latest \
            --jq '.tag_name')

          if [ -z "$LATEST_RELEASE_TAG" ]; then
            echo "::warning::Could not find a latest release in $SOURCE_REPO. Skipping external download."
            exit 0
          fi
          
          echo "Found latest release tag: $LATEST_RELEASE_TAG"
          
          SOURCE_REPO_NAME=$(basename $SOURCE_REPO)
          EXPECTED_ASSET_NAME="${SOURCE_REPO_NAME}-${LATEST_RELEASE_TAG}.zip"

          gh release download $LATEST_RELEASE_TAG \
            --repo $SOURCE_REPO \
            --pattern $EXPECTED_ASSET_NAME \
            --dir $DOWNLOAD_DIR \
            --clobber
          
          echo "Finished downloading $EXPECTED_ASSET_NAME to $DOWNLOAD_DIR."

      - name: Generate and Create New Tag
        run: |
          BASE_TAG="v1.5.12-r0"
          LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="$BASE_TAG"
          else
            LATEST_TAG=$(printf "%s\n%s\n" "$LATEST_TAG" "$BASE_TAG" | sort -rV | head -n1)
          fi
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts
          
      
      - name: Generate Device List and Final Release Notes
        id: generate-notes
        run: |
          echo "=== Start building the release notes ==="
          cat << EOF > release_notes.md
          This release contains KernelSU Next and SUSFS v1.5.12
          
          Module: 
          -> https://github.com/sidex15/ksu_module_susfs  
          
          Official Managers:
          -> https://github.com/KernelSU-Next/KernelSU-Next  
          
          Non-Official Managers:
          -> https://github.com/WildKernels/Wild_KSU
          
          ### Built Devices
          
          | Model | Kernel Version |
          |-------|----------------|
          EOF
          
          # Generate table rows
          for file in $(find downloaded-artifacts -name "*.txt" -type f | sort); do
            if [ -f "$file" ]; then
              model=$(basename "$file" .txt)
              version=$(cat "$file")
              printf "| %-12s | %-16s |\n" "$model" "$version" >> release_notes.md
            fi
          done
          
          # Add features and finalize
          cat << 'EOF' >> release_notes.md
          
          ### Features
          - [+] KernelSU-Next / WildKSU Manager Support
          - [+] SUSFS v1.5.12
          - [+] Wireguard Support
          - [+] Magic Mount Support
          - [+] Ptrace message leak fix for kernels < 5.16
          - [+] Manual Hooks [scope_min_manual_hooks_v1.4]
          - [+] CONFIG_TMPFS_XATTR Support [Mountify Support]
          - [+] BBR v1 Support
          - [+] Baseband Guard Support (BBG)
          - [+] Nethunter Support
          - [+] xx_maps hide
          - [+] Mem kernel driver by @Poko-Apps [r/w to physical memory]
          EOF
          
          # Output for debugging
          echo "--- Final Release Notes ---"
          cat release_notes.md

      - name: Create GitHub Pre-release
        if: ${{ inputs.release_type == 'Pre-release' }}
        run: |
          gh release create "${{ env.NEW_TAG }}" \
            --repo "${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}" \
            --title "*Test-build*-${{ env.RELEASE_NAME }}-*Test Build*" \
            --notes-file release_notes.md \
            --prerelease
       
      - name: Create GitHub Release
        if: ${{ inputs.release_type == 'Release' }}
        run: |
          gh release create "${{ env.NEW_TAG }}" \
            --repo "${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}" \
            --title "${{ env.RELEASE_NAME }}" \
            --notes-file release_notes.md

      - name: Upload Release Assets Dynamically
        run: |
          for file in ./downloaded-artifacts/*/*.zip; do
            if [ -f "$file" ]; then
              echo "Uploading $file..."
              gh release upload "${{ env.NEW_TAG }}" "$file" --clobber
            fi
          done
